### ISSUE TITLE
Apple Pay active in BO but it does not show up at front

### ISSUE THREAD

**Issue by Saimis777** [mollie/PrestaShop1.7#295]
### Expected behavior
Apple pay should display in front office

### Actual behavior
When enabled Apple pay isn't showing in the front office

### Steps to reproduce the behavior
Enable Apple pay in the back office, try to checkout and pay with Apple pay.

### Environment
* PrestaShop version: 
* Mollie module version: 4.2.2
* PHP version:

**Comment by MariannevdS** [comment]
Ok we have PS 1.7.7.1
Mollie Module version 4.2.2
php: 7.1.34

Mollie works really well all payment work except for the Apple pay method.

It is activated in our account and activated in the BO but it does not shop up in front
![Schermafbeelding 2021-02-18 om 19 26 06](https://user-images.githubusercontent.com/78209224/108403684-44472d00-721f-11eb-88e7-b9ed2816d790.jpg)

**Comment by Saimis777** [comment]
@MariannevdS ,

Thank you for the additional information! And could you also clarify when entering this page - https://applepaydemo.apple.com/ what does it show for you in the grey box?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
That depends in which browser I open it, in Firefox it says browser does not support, in Safari i can do a test payment.
But when I open our webshop in safari or on Iphone, it does not show the apple pay payment option

![Schermafbeelding 2021-02-19 om 09 46 22](https://user-images.githubusercontent.com/78209224/108480851-c115ed80-7297-11eb-995b-23e21a4197ca.jpg)

**Comment by Saimis777** [comment]
@MariannevdS,

Thank you for the clarification, for further investigation we would need credentials of your BO/SSH or FTP, you would need to send them to support@invertus.eu, would that be possible?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @MariannevdS ,

Could you clarify if further details can be provided for the investigation?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
I cannot give you all the credentials to the live site, I have a clone though that I can give you acces to with the same problems. I send them to you

**Comment by Saimis777** [comment]
Hello!

No worries, if you have a clone that has the same environment, and
encounters the same issue, that would work as well!

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still working on this case, and I will update you once I'll receive further clarifications from the development team.

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still working on the case, and are testing it internally, will clarify regarding this matter on Monday.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @MariannevdS ,

As this is an issue related to the specific one page checkout modules which have specific controllers, we are checking out what are the best options that we can implement to make the one page checkouts work with Mollie.

I will update you as soon as possible regarding this case!

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @MariannevdS ,

Indeed an interesting find, also what we found is that the checkout module that your shop is using claims: "Supports ANY shipping and payment method ()() If your shipping or payment methods does not work yet, we guarantee FIX or REFUND." 

Could you clarify if you've tried contacting your module's support regarding this case? As if it guarantees to work, they would need to implement the fix for it to work with Mollie as well from what I can see, since there are no other cases at the moment reported to have an issue with Apple pay.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
Thank you, i will contact the module-builders and ask. 

Hartelijke groet,

Marianne van der Sluis

**Comment by Saimis777** [comment]
@MariannevdS ,

Be sure to let us know how it will go!

And if our assistance will be needed!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
Hi, 
Before I contacted the module-builder I turned off the one-page-checkout module and in the "normal" checkout procedure I 
found the same issue, see screenshot, "
![Schermafbeelding 2021-03-15 om 15 44 07](https://user-images.githubusercontent.com/78209224/111172038-c409b280-85a5-11eb-9c31-5647867a87ac.jpg)
no apple pay"

**Comment by Saimis777** [comment]
Thanks for the additional information @MariannevdS!

We are checking this out further.

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
Hello,

I am sorry, I was wrong!!
I did not try in the right browser!
I checked in firefox before and ofcourse did not see apple pay. 
I checked in safari just now and it is there. 

I will ask the “ the checkout” -module module builder

Hartelijke groet,

Marianne van der Sluis

**Comment by Saimis777** [comment]
@MariannevdS ,

Thank you for the clarification! 

I am going to close this issue for now, let us know once you will receive a solution from the module developers and if it will solve your problems!

If not, we are going to re-open this issue, and continue on with the investigation, we are here to help!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello community!

Just wanted to inform everyone that in the next release of Mollie we will include an implementation that has a general controller for one page checkout modules, so there should be no issues with 3rd party One page checkout modules in the next release.

Let me know if you have any questions regarding this case!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

A new version of Mollie was just released, with a fix included, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.4

We are closing this issue for now, if the issue is still there be sure to let us know, we'll reopen the issue!

And be sure to provide us feedback regarding the latest release!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@MariannevdS did you solve this issue? As we have the exact same problem with Mollie 5.0.1 and TheCheckout module. Apple Pay is not showing up on iPhone (with Apple Pay enabled).

**Comment by justelis22** [comment]
Hey there, @wzzly!

Could you please send us the steps to replicate the issue and FTP+BO credentials to support@invertus.eu so that we could check this out for you?

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
@wzzly 
I used a fix for the Mollie-module:

In this file:
Root/modules/mollie/**mollie.php**

Added this line:
// thecheckout module
        $isOPCController = $isOPCController || $this->context->controller instanceof TheCheckoutModuleFrontController;

**Comment by wzzly** [comment]
@MariannevdS  thanks voor the reply. Where in the file did you add it? Before the "class Mollie extends PaymentModule" line of inside the Mollie class?

@justelis22 is it possible to add this in future update?

**Comment by MariannevdS** [comment]
**In this section:**
	 * @throws PrestaShopException
	 */
	public function hookActionFrontControllerSetMedia()
	{
		/** @var \Mollie\Service\ErrorDisplayService $errorDisplayService */
		$errorDisplayService = $this->getMollieContainer()->get(\Mollie\Service\ErrorDisplayService::class);

		$isOrderController = $this->context->controller instanceof OrderControllerCore;
		$isOPCController = $this->context->controller instanceof OrderOpcControllerCore;
		$isCartController = $this->context->controller instanceof CartControllerCore;

		**// thecheckout module
		$isOPCController = $isOPCController || $this->context->controller instanceof TheCheckoutModuleFrontController;**

		if ($isOrderController || $isOPCController) {
			$errorDisplayService->showCookieError('mollie_payment_canceled_error');

			Media::addJsDef([
				'profileId' => Configuration::get(Mollie\Config\Config::MOLLIE_PROFILE_ID),
				'isoCode' => $this->context->language->language_code,
				'isTestMode' => \Mollie\Config\Config::isTestMode(),
			]);
			if (\Mollie\Config\Config::isVersion17()) {
				$this->context->controller->registerJavascript(
					'mollie_iframe_js',
					'https://js.mollie.com/v1/mollie.js',
					['server' => 'remote', 'position' => 'bottom', 'priority' => 150]
				);
				$this->context->controller->addJS("{$this->_path}views/js/front/mollie_iframe.js");
			} else {
				$this->context->controller->addMedia('https://js.mollie.com/v1/mollie.js', null, null, false, false);
				$this->context->controller->addJS("{$this->_path}views/js/front/mollie_iframe_16.js");
				$this->context->controller->addJS("{$this->_path}views/js/front/mollie_payment_method_click_lock_16.js");

**Comment by MariannevdS** [comment]
Oh and for updates... The **developer of the checkout module** is the one who can fix this, they wanted to put it into the next version but made no promise.

I have not updated that one since then so i don't know if they did

**Comment by justelis22** [comment]
@wzzly,

Please let me know if the provided suggestion helps with the issue.
As for the fix, we have already done it from our side on the 4.2.4 release.

Waiting for your update!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@MariannevdS @justelis22 

I also contacted the module developer and this was his reply:

`This is probably a known problem from the mollie module side, and I implemented a fix into modules/mollie/mollie.php as described here: https://github.com/mollie/PrestaShop1.7/wiki/Known-Issues#One-page-checkout-modules-not-working-with-Apple-Pay

Basically, I edited mollie.php, to add:

      // thecheckout module

      $isOPCController = $isOPCController || $this->context->controller instanceof TheCheckoutModuleFrontController;

See where exactly: https://i.imgur.com/QH2VY0h.png

Regards,

-peter.`

As the fix is in mollie.php, shouldn't it be added to the mollie module?
I will try this fix and let you know if it works

**Comment by wzzly** [comment]
tried the fix but it's not working. Looks like the mollie code has changed in the latest versions as there is no more `$isOPController` in the current mollie.php file.

This is where I now placed the fix:
![image](https://user-images.githubusercontent.com/35727938/169804075-48ea3b36-b4b9-40f6-98b8-3340387d2008.png)

**Comment by justelis22** [comment]
Hey there, @wzzly!

Our developer was able to replicate the issue from his side, it seems like it is coming from Mollie's side.
If you would like to fix this right now, you can use this solution - change hookDisplayHeader from:
```
if (!$this->context->controller instanceof OrderController) {
    return;
}

if (!$this->isPaymentCheckoutStep()) {
    return;
}
```
To
```
if ($this->context->controller->php_self !== 'order')
{
    return;
}
```

Let us know if that helps!

This issue should be fixed in the upcoming release.

Best regards,
Invertus Support team.

**Comment by wzzly** [comment]
@justelis22 

ok nice! Any idea on the ETA for the new release?

**Comment by justelis22** [comment]
Hey there, @wzzly,

We are expecting the new release next Tuesday 👍

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there,

The new release has come out already, and this issue should have been fixed.
If you are still facing it, do let us know, and we will make sure it is solved.
For now, we are going to close this issue.

Best regards,
Invertus Support team.
