### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by pic16f876** [mollie/PrestaShop1.7#522]
### Expected behavior
Description in payment details as set. In this case order nr

### Actual behavior
It works allright with creditcard payments, but not with ideal. With ideal payments the description is mol_339461f9774c9a5xxxxxxx

### Steps to reproduce the behavior
Make a payment with ideal and have {orderNumber} set in description with payment api. Works with creditcard, but not ideal. Same api, same setting

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 5.0.0
* PHP version: 7.3.33
![Screen Shot 02-02-22 at 12 31 PM](https://user-images.githubusercontent.com/67101966/152145870-7ae46b1c-6659-4681-877c-4a8913f17590.PNG)

**Comment by pic16f876** [comment]
I also had the issue in 4.4.3.

**Comment by loonas** [comment]
Hi @pic16f876! I hope that you are doing well.

Thank you for your query. We appreciate your interest in perfecting the Mollie module!
I have forwarded the details to the developer to check it out. We will keep you updated about the progress.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @pic16f876!

Could you let us know how your iDeal set up looks like in the Prestashop Back Office? A screenshot would be great and would help us investigate.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by pic16f876** [comment]
![Screen Shot 02-02-22 at 03 04 PM](https://user-images.githubusercontent.com/67101966/152169248-0ab15043-b493-429b-8af2-7f1037e5c0b0.PNG)
![Screen Shot 03-08-21 at 03 40 PM](https://user-images.githubusercontent.com/67101966/152169256-653c04db-66c4-467d-ac6a-e786007b4901.PNG)

I added ideal and cc settings

**Comment by pic16f876** [comment]
![Screen Shot 02-02-22 at 03 03 PM](https://user-images.githubusercontent.com/67101966/152169362-deb0925f-b6ff-4a79-a278-a5c77ff32c67.PNG)
![Screen Shot 02-02-22 at 03 04 PM](https://user-images.githubusercontent.com/67101966/152169364-530d04f3-aa39-4db8-a740-174c639e10c9.PNG)

I Added both screenshots for ideal and creditcard

**Comment by loonas** [comment]
Thank you @pic16f876!

I have forwarded the following information to the developer to investigate further. We will keep you updated!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @pic16f876! Hope that you are well.

Our developer has checked the issue and has added validation in the Settings page to now allow to save only empty spaces. Along with that, a validation was added to check if generated description is not empty and space only, if it is, then it changes it to the order reference so that the issue would not appear again.

We have included the fix in our latest 5.0.0 release, you can find it right [here](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0).

We are looking forward to your questions or feedback!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @pic16f876! I hope that you are doing well.

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

Best regards,
Invertus Support team
