### ISSUE TITLE
Orders not created after payment after update Prestashop from 1.6.1.4 to 1.7.8.5 and update Mollie module to 4.4.3 or 5.01

### ISSUE THREAD

**Issue by viki1974** [mollie/PrestaShop1.7#562]
### Expected behavior
After correct payment orders in Prestashop is not created.

### Actual behavior
I updated Prestashop from 1.6.1.4 to 1.7.8.5. After that, the old version of Mollie 3.5.X still works, but I did upgrade to 5.01. After that, there is a problem with creating orders. Mollie receives payments, but no orders are created. Noticed what old orders in payment table in Mollie admin panel is have details with card number like 'Cart 86624', new order is have details like 'mol_8665362592a5f69f8d16500XXXXX'

I did a complete removal of the module and installed version 4.4.3 - all the same.

### Steps to reproduce the behavior
create and pay an order in LIVE mode

### Environment
* PrestaShop version: 1.7.8.5
* Mollie module version: 4.4.3
* PHP version: 7.3.33

**Comment by justelis22** [comment]
Hi @viki1974! Hope that you are doing well.

Thank you for raising this issue with us. 

As the previous version was 3.5.5 or any lower, then the module needs to be uninstalled completely. The module was refactored with v4 and settings require complete deletion from the shop before installing the module.

Could you please delete the module, and install the latest one?

If that will not help, we would need your BO + FTP credentials sent to - [support@invertus.eu](mailto:support@invertus.eu)

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by viki1974** [comment]
Full uninstalling has helps. Thank you for support.
