### ISSUE TITLE
"Refund All" button not working properly, quantities mismatch

### ISSUE THREAD

**Issue by gurkcity** [mollie/PrestaShop1.7#563]
### Expected behavior
Quantities should have correct values after refund

### Actual behavior
The quantities do not match those in the "Check order" popup

### Steps to reproduce the behavior
When you click the "Refund All" button on an order in Mollie, you can refund all items or adjust the quantity:
![grafik](https://user-images.githubusercontent.com/2813604/163986106-aa08996e-b529-4f33-af4e-06d6871a66ec.png)

In the Popup (1) you are able to set the quantities. After clicking OK you can see the result (2) in the mollie information table. The returned quantities do not match the selected quantities in popup:
![grafik](https://user-images.githubusercontent.com/2813604/163986490-9b03697e-9c24-4c86-a9eb-d1156cba746d.png)

If we do this refund in Mollie backend this works as expected. Here with the same order and impact on PrestaShop Mollie information table on orders page (left side shows the Mollie backend, right side the PS):
![grafik](https://user-images.githubusercontent.com/2813604/163986720-9f0dba32-a7dc-4a5a-8f24-1deae23e4e0f.png)

### Environment
* PrestaShop version: 1.7.6.8 
* Mollie module version: 5.0.1
* PHP version: 7.2.34

**Comment by justelis22** [comment]
Hello there @gurkcity!

Thanks for contacting us!

This issue could be caused because the refunds from your Mollie account are still pending, and they could not be issued a second time. Just to be sure, could you attach a screenshot with the list of the same refunds as attached in the screenshots above. It will look like this:
![image](https://user-images.githubusercontent.com/103486043/163994270-e5ca596b-b5f7-499f-bd92-127a780f8b00.png)
This will help you understand the issue more clearer!

Waiting for your update!

**Comment by gurkcity** [comment]
Hello @justelis22 
thanks for helping. This issue has nothing to do with the status. Please try yourself:
1) fill a basket with 3 different products, buy each of them 3 times with Mollie payment
2) in BO order page do a mass part refund like screenshot above, but refund not complete
refund first product 3 times, the second 2 times and the third 1 item.

I will create another example to reproduce this issue in a demo shop and provide a new screenshot here

**Comment by justelis22** [comment]
Hello there!

Could you share your BO+FTP credentials to [support@invertus.eu](mailto:support@invertus.eu), so that our developer could check the issue out?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by justelis22** [comment]
Hi @gurkcity,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions or when you would like to continue!

Best regards,
Invertus Support team.

**Comment by gurkcity** [comment]
Hi @justelis22 ,
the problem is not resolved. I have a meeting tomorrow with my client. We will prepare a demo site you can check on. Due to gdpr regulations and data protection we can't give you access to our live site with BO + FTP credentials. So please be patient. I will come back to you as soon as possible.
Chris

**Comment by justelis22** [comment]
Hey there, @gurkcity!

Thank you for updating us, we will be waiting for your reply, so take your time!

Best regards,
Invertus support team.

**Comment by gurkcity** [comment]
Hi @justelis22 
I just have send you an email with demo access
Thanks for helping.
Kind regards
Chris

**Comment by justelis22** [comment]
Hello there, @gurkcity!

Thank you for the details, we have received them. As soon as we have an update, we will let know!

Best regards,
Invertus support team.

**Comment by justelis22** [comment]
Hi @gurkcity,

Due to inactivity, I will close this issue. Let us know if you will have any other questions or when you would like to continue!

Best regards,
Invertus Support team.
