### ISSUE TITLE
When downloaden current version from Addons, it show not-up-to-date

### ISSUE THREAD

**Issue by vanengers** [mollie/PrestaShop1.7#570]
### Expected behavior
Show up-to-date

### Actual behavior
Showing not up-to-date, there is a newer version

### Steps to reproduce the behavior
Download new from addons..

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: 5.0.1 
* PHP version: 7.1.26 

There are 2 versions on github which are in BETA.. 
When uploading the beta versions into a production shop, it shows errors and can't use the module. (but probably there are work-arounds fot that.. this is not the issue).

When downloading (reverting) to the addons current version it shows it's not up-to-date.
But then again, can't update to the Beta versions in Production..
![Moll2](https://user-images.githubusercontent.com/39123706/168221153-001177cf-3a6e-421d-a0c4-95ac877c5e22.JPG)

**Comment by justelis22** [comment]
Hello there, @vanengers!

Thank you for the details, we have received them and forwarded them to our team. As soon as we have an update, we will let know!

Best regards,
Invertus support team.

**Comment by justelis22** [comment]
Hello there, @vanengers! 

Thank you for bringing our attention to this :)

We have noticed that there are some issues with the beta2 version, as it seems like it could not be upgraded properly.
The yellow message regarding the versions will be updated, that it would only consider the actual release and not pre-release.
We will let you know when the issues with beta2 are fixed, and once you are able to upgrade.

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey there, @vanengers, I hope you are doing alright today!

I would like to note that the issue with the upgrade to the beta2 version was already fixed, and you can now try it out without any issues.

We will be waiting for your feedback!

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey there, @vanengers!

As this case was not updated for some time now, I will close it.

If you have any questions let us know, and for now take care and have a nice day!

Best regards,
Invertus support team.
