### ISSUE TITLE
Apple Pay not available in Payment list front-end

### ISSUE THREAD

**Issue by RVanDamage** [mollie/PrestaShop1.7#586]
Hi there,

We have lots of customers running on PrestaShop using Mollie module.
And today I realised that for none of them the Apple Pay method is available when checking out on front-end. I knew this, but never really payed attention to it, thought maybe you had to been using an Apple device while checking out and it may did appear.

However, it's enabled and accepted in Mollie dashboard, and also enabled with green check icon in Mollie module, but just not visible in front-end, while all the other Mollie payment methods are showing.

Should we do something special for this?

**Comment by justelis22** [comment]
Hey there, @RVanDamage!

To see the Apple Pay payment method you have to be using an Apple device and Safari browser. 
If you are using them and you are still not seeing Apple Pay in the Front Office, please send us FTP+BO credentials to support@invertus.eu and we will investigate this issue.
Waiting for your update!

Best regards,
Invertus Support team.

**Comment by RVanDamage** [comment]
Hi @justelis22,

Thank you for the quick respons.

I just tried two shops, with my iPhone and Safari. On is on Mollie module latest version 5.1
The other one is on Mollie 5.0.1 

Both have no Apple Pay :(

**Comment by justelis22** [comment]
@RVanDamage,

Could you please send us the credentials to access the shop, so that we could investigate further?

Best regards,
Invertus Support team.

**Comment by RVanDamage** [comment]
Hi @justelis22,

I just send credentials to [support@invertus.eu](mailto:support@invertus.eu)

Keep me posted :)

**Comment by justelis22** [comment]
@RVanDamage,

We have received the credentials, as soon as we have an update, we will let you know!

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey there, @RVanDamage!

I was able to replicate the issue from our side as well.
Could you please verify whether you have already tried to [follow these steps](https://github.com/mollie/PrestaShop1.7/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office)?

Waiting for your feedback!

Best regards,
Invertus Support team.

**Comment by RVanDamage** [comment]
Hi @justelis22,

Yes I tried them but no luck. I will try on other shop later.

So other than that we can only reinstall module? But first fully remove module? Do we need to remove some database tables manually?

**Comment by justelis22** [comment]
Hey, @RVanDamage, thank you for waiting!

Could you please confirm whether we can try to update the module on your shop?

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello, @RVanDamage!

Glad to hear that, is everything fine at the moment? Can we close the issue?

Best regards,
Invertus Support team.
