### ISSUE TITLE
When your are employee with other permissions you see not the order mollie info when view order in backoffice

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop1.7#590]
### Expected behavior
Other rights as employee account in backoffice can also see MOLLIE information.

### Actual behavior
When your are employee with other permissions you see not the order mollie info when view order in backoffice

**Comment by tajriba** [comment]
![image001-3](https://user-images.githubusercontent.com/68469531/177336225-df67c83b-b95e-4cb4-8800-739f7f9854f1.png)

**Comment by justelis22** [comment]
Hello there, @tajriba!

We have received your request, we will investigate and come back to you with an update!

Best Regards,
Invertus Support team.

**Comment by tajriba** [comment]
Hi! Thank you, it works!

**Comment by justelis22** [comment]
Hey there, @tajriba!

Glad to hear that it is working fine!
We will mark this issue as resolved, but if you have any additional questions, don't hesitate to contact us!

Best Regards,
Invertus Support Team.
