### ISSUE TITLE
Class \"AdminMollieAjaxControllerController\" not found in controllers/admin

### ISSUE THREAD

**Issue by drwebbe** [mollie/PrestaShop1.7#592]
### Expected behavior

https://webshop.poujoulat.de : Payment choice in checkout

### Actual behavior

No payment option available : Keine Zahlungsmethode zur Verfügung steht.
When activating default PS wiretransfer payment option, that option shows up, but not Mollie.

### Steps to reproduce the behavior

Simply go to checkout, select Germany as country.

### Environment
* PrestaShop version: 1.7.6.8
* Mollie module version: 5.2
* PHP version: 7.3.31

**Comment by drwebbe** [comment]
Hi,
I've activated and desactivated the test option.
When testing the API key I get :
 Test API-key: Success!
Enabled Methods: applepay, ideal, creditcard, in3, klarnapaylater, klarnapaynow, klarnasliceit, paypal, banktransfer, sofort, giftcard, bancontact, eps, giropay, przelewy24, kbc, belfius, voucher, directdebit

Live API-key: Success!
Enabled Methods: applepay, ideal, creditcard, in3, klarnapaylater, klarnapaynow, klarnasliceit, paypal, banktransfer, sofort, giftcard, bancontact, eps, giropay, przelewy24, kbc, belfius, voucher, directdebit

In the Front-end, no payment options show up (wether it's live or Test).
The payment options are enabled for all types of customers, delivery-options, country (Germany only).

**Comment by drwebbe** [comment]
When enabling Test, I can choose and enable the different payment options in the backoffice, and then they show up in the front.
When I then enable the live option, I can't enable the payment options in the backoffice and ofcourse, no payment options show up in the front.

**Comment by EdouardBayon** [comment]
Hello there,

Quick question:
Are your payment method fully activated in your Mollie dashboard as well ? (they should be blue)

**Comment by drwebbe** [comment]
Problem solved, the account was disabled by Mollie themselves.

**Comment by justelis22** [comment]
Glad to hear that!

If anything, don't hesitate to contact us, we will be here to help you.

--
Best Regards,
Invertus Support team.
