### ISSUE TITLE
Multishop breaks the Mollie configuration

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop1.7#593]
### Expected behavior
Each shop can have multiple payment methods (Credit card, Paypal, Klarna...).
When I select the shop, I can specify payment options and payment methods for my shop.

### Actual behavior
When I save the configuration, it breaks all the configurations of the other shops.

### Steps to reproduce the behavior
- Config payment methods for one shop (change the name, countries for each methods, options...).
- Change to an other shop
- Config the other shop and save
- It breaks the previous shop configuration by default

### Environment
* PrestaShop version: 1.7.7.5 
* Mollie module version: 5.1 
* PHP version: 7.1.26

**Comment by justelis22** [comment]
Hey there, @AnatoleRozan!

We have received your request, our team will overview the provided information, and we will get back to you!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@AnatoleRozan,

We have tried to replicate the issue from our side by installing the latest version of the Mollie module of the newly installed PrestaShop, and everything seems to be alright, we were able to see correctly selected payment methods of different shops of the multistore.
The first thing we would recommend is to install the latest version of the Mollie module, which is 5.2.0.
Also, make sure you are clearing cache before testing everything out just to be sure you are not seeing old content.
Please let us know if that improves your current situation.

--
Best Regards,
Invertus Support team.

**Comment by AnatoleRozan** [comment]
Thanks for your quick reply @justelis22.
We'll test again with new shops, later today. 

I'll share a you a video of the problem on our shop. Can you send me your e-mail?

**Comment by justelis22** [comment]
Hey there, @AnatoleRozan!

We have not received an email from you, do you have any updates? Perhaps you were able to fix the issue?

--
Best Regards,
Invertus Support team.

**Comment by AnatoleRozan** [comment]
I've sent you the issue. It doesn't save properly the order of payment methods and remove the customs.

**Comment by AnatoleRozan** [comment]
I don't understand how you test your plugin before launching. This bug is obvious when you test a plugin properly...

**Comment by justelis22** [comment]
Hello there, @AnatoleRozan,

We have received your videos of the issue. While checking the videos, we noticed that you are not using the latest version of the module, so before starting to investigate, please upgrade your module version. You can find it here -https://github.com/mollie/PrestaShop1.7/releases

--
Best Regards,
Invertus Support team.

**Comment by Kommertje** [comment]
We have same problem here (this is a problem from the beginnnig of your module). Only when we change the settings in Main store, it keep the payment settings of the other stores. If we update payments from other stores, payment settings wil reset to standard and we have to set everything up again. If you edit in the correct order (main store first, then the other stores), it will be preserved.

**Comment by AnatoleRozan** [comment]
@Kommertje we're working with the Invertus team on the bug. They have received all elements to patch it. Maybe in few days.

**Comment by justelis22** [comment]
Hello there, @Kommertje!

We have implemented a fix, thanks to @AnatoleRozan for cooperation by providing his testing results and helping us to fix the issue faster.
The fix will be added to the 5.3.0 release, but if the issue is causing you difficulties, please contact us at support@invertus.eu, and we will send you the fix before the release.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,
I hope you are doing alright!

We just wanted to let you know that we have released the [5.3.0 beta version](https://github.com/mollie/PrestaShop1.7/releases). We have fixed this issue, so we would recommend updating the module.

If you find any issues or have some feedback, let us know!
