### ISSUE TITLE
Order state is not set

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop1.7#598]
### Expected behavior
Set correct order statuss

### Actual behavior
When we do in LIVE modus a refund for order in this screen, the order state is again set to PAID instead of REFUND.

### Steps to reproduce the behavior
Refund order , open order > order details > refund from there in backoffice prestashop
<img width="2325" alt="Schermafbeelding 2022-07-26 om 13 19 17" src="https://user-images.githubusercontent.com/68469531/180994000-b21388b2-b826-488b-80a2-2217bc48ebfa.png">

### Environment

* PrestaShop version: 1.7.6.9
* Mollie module version: 5.2.0 
* PHP version: 7.3

**Comment by justelis22** [comment]
Hey there, @tajriba!

We have received your request, our team will overview the provided information, and we will get back to you!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@tajriba,

Please check the status of the order on your account at Mollie.com. The status does not change immediately, as the order status is changed to "Pending Refund" from the Mollie side.

Please verify if that is the case, we will be waiting for your feedback!

--
Best Regards,
Invertus Support team.

**Comment by tajriba** [comment]
@justelis22 the problem is: the order state is not set to "refunded" in prestashop. 
Also, it gives the order the order state : Paid again.

**Comment by justelis22** [comment]
@tajriba,

Could you clarify what is the status from Mollie's side? As the status is being taken from the Mollie side, so it is only changed on the Prestashop side once it is set to refunded there.
There is a delay, as we provide a time to cancel the refund, once that time ends, pending status changes to refunded and you are no longer able to cancel the refund.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there,

As this issue was inactive for some time now, we are going to close it.
If you have any additional questions, let us know.
In the meantime, have a nice day!

--
Best Regards,
Invertus Support team.

**Comment by tajriba** [comment]
@justelis22 Hi, on the mollie side it has done the state refunded. But it place the order again on payment accepted instead of refunded while the order state settings are correct in the mollie plugin.

**Comment by justelis22** [comment]
Hey there, @tajriba!

Could you please send us the credentials to access your shop and files (BO+FTP+SSH) to support@invertus.eu?
Screenshots or a video explaining the issue in more detail would be really helpful as well!

Waiting for your message!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey there, @tajriba!

As this issue was inactive for some time now, we are going to close it.
Once you come back, please send us the required information.

--
Best Regards,
Invertus Support team.
