### ISSUE TITLE
Aligning icons at check out 

### ISSUE THREAD

**Issue by VanDalICT** [mollie/PrestaShop1.7#609]
### Expected behavior
I want to align the icons that show up at the end 
![image](https://user-images.githubusercontent.com/115456792/194826450-1dc0717e-b235-4c44-a001-8838f97c3c0e.png)
I can't seem to align these icons now matter how much I try to edit the main variable

### Actual behavior
I tried adding a table to get them nice and evenly but it conflicts with the structure of how paymentoptions works. Its a javascript template on its own and it doesnt work with a table, is there anyway to make the icons line up properly like this?
![image](https://user-images.githubusercontent.com/115456792/194827587-c85f676e-24a0-4345-a8e9-b6e0a5acc69f.png)

Kind regards,

VanDalICT

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 3.3.4 
* PHP version: 7.1.26

**Comment by justelis22** [comment]
@VanDalICT,
Thanks for updating the case!

We would like to note that we are using the default PrestaShop logic for this.
So in this case, if you would like to modify the payment method icon location/placement you would need to modify the core or your theme files.

I hope that explains how it works!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

As this issue did not update for some time now, we are going to mark it as resolved.

If you have any additional questions, let us know!

Best Regards,
Invertus Support team.
