### ISSUE TITLE
Payment fee not showing & update total amount.

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop1.7#613]
### Expected behavior
Payment amount fee should show and also update the total amount of the cart.

### Actual behavior
Payment fee amount is hidden en not updating the total amount of cart, only visible when going to the payment screen.

### Steps to reproduce the behavior
Enable payment fee. * note whe are using an 3th party shoppingcart module ( supercheckout)

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: 5.2.1
* PHP version: 7.4.32

**Comment by justelis22** [comment]
Hi there,

We will check, and get back to you with an update!

Best Regards,
Invertus Support team.

**Comment by Maikel726** [comment]
Hi,

The issue is fixed.

**Comment by justelis22** [comment]
Hi there @Maikel726,

Great news!
Could you please clarify what have you changed?

Best Regards,
Invertus Support team.

**Comment by Maikel726** [comment]
Hi.

I've contacted the creator of the one pagecheckout and they did some changes.

**Comment by justelis22** [comment]
Hi there,

As this case is related to one page checkout modules, we are going to close it.

If you have any additional questions, let us know!

Best Regards,
Invertus Support team.
