### ISSUE TITLE
Entries in PS Logs about errors with API call

### ISSUE THREAD

**Issue by CooUoo** [mollie/PrestaShop1.7#637]
Hello,

I have strange messages in the Prestashop Logs.
All have the same structure, only the payment reference changes.
I put here some xxxx instead of the real payment reference.

> Mollie module error: [2023-01-09T10:24:19+0100] Error executing API call (404: Not Found): Payment tr__xxxxxxx_ exists, but the wrong mode is used. Try switching live / test API keys.. Documentation: https://docs.mollie.com/overview/handling-errors

I don't understand, because I'm in live mode, payments work normally, so... I don't know why I get these messages.
It's very strange, because these payments can be 2-3 months old.

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: 3.5.1
* PHP version: 7.3

**Comment by justelis22** [comment]
Hey there,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @CooUoo,

I can see that you are using the 3.5.1 Mollie module version, could you please try to upgrade the module to the latest one and see if that helps with the issue? You can download the latest release here - https://github.com/mollie/PrestaShop1.7/releases/tag/5.3.1

Keep me updated!

--
Best Regards,
Invertus Support team.

**Comment by CooUoo** [comment]
Hello,

Sorry, I made a typing mistake.
I do use the last 5.3.1.

Regards

**Comment by justelis22** [comment]
Hi there,

It seems like the API could have been changed. Orders can be created but something else could not be working properly, as the webhook displays the message that you have attached.
Please try to check the transaction on your account mollie.com, and check if all of the information is matching if the API key is correct and live.

If you have any questions, let us know!

Best Regards,
Invertus Support team.

**Comment by CooUoo** [comment]
Hi

I checked every info.
Everything is correct on my shop and on mollie.com.
I can even see the lines in the history of each order "Webhook called successfully..."

That being said, I don't see any malfunction, i.e. orders are ok, payments are ok, refunds are ok...
Everything works as expected.

So, if there is an error somewhere, it doesn't seem to affect our activity.
But still... I don't like non-understood error messages like this.

Regards

**Comment by justelis22** [comment]
Hi there @CooUoo,

We will continue investigating next week, in the meantime, could you please send us your Back-Office and FTP credentials to support@invertus.eu?

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @CooUoo,

We have not received the information from your side for some time now, so we are going to close this issue.
If you face this issue once again, please let us know, and we will reopen the ticket.

Best Regards,
Invertus Support team.
