### ISSUE TITLE
Sepa Direct credit not shown in configuration 

### ISSUE THREAD

**Issue by steefv911** [mollie/PrestaShop1.7#639]
### Expected behavior
We have activated SEPA Incasso in Mollie dashboard. 
We expect to see this option now in our check out in prestashop. 

### Actual behavior
We do not see any option to show, enable or activate the SEPA Incasso in Prestashop admin. 

### Environment
* PrestaShop version: 1.7.8.5
* Mollie module version: 5.2.1

Is this feature already build in the module? If not are you planning to? And if not, are we able to develop this together with our developer?

**Comment by justelis22** [comment]
Hey there,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @steefv911,
Thanks for waiting!

SEPA direct debit is not build in the module, at the moment it is not in the module development roadmap to build it. If you would like to develop it, you would need get the approval from Mollie, however you should be aware that out of that custom code it will be hard for us to provide support.

One-off SEPA Direct Debit payments using Mollie Checkout can only be created if this is enabled on your account. In general, it is not very useful for webshops but may be useful for charities.
To enable this, you would need to contact Mollie support department.

If you want to use recurring payments, take a look at our [Recurring payments guide](https://docs.mollie.com/payments/recurring).

We are going to mark this issue as resolved, but if you have any additional questions, please let us know!

--
Best Regards,
Invertus Support team.
